image:
  file: Dockerfile
ports:
  - port: 8001
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
vscode:
  extensions:
    - felixfbecker.php-debug@1.13.0:WX8Y3EpQk3zgahy41yJtNQ==
tasks:
  - init: composer install;
          gp preview $(gp url 8001)
  - name: Git
    command: >
        git clone https://github.com/constantinjoly/512 themes/512
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log
